# ExtractionChest Configuration
# Plugin version: ${project.version}

# General settings
settings:
  debug: false
  prefix: "&8[&bExtractionChest&8]&r"

# Region settings
region:
  always-show-regions: false
  replenish-batch-size: 5
